### ISSUE TITLE
Users may work on cards / tasks on expired sprints

### ISSUE THREAD

**Issue by ivanilas** [flying-donut/flying-donut-operations#12]
The users may work on cards / tasks on expired sprints. Maybe there should be a project setting to be able to automatically lock the inactive sprints (expired and future).

**Comment by pkouleri** [comment]
IMHO we should leave this as is. There might indeed be a need to work on "expired" sprints without wanting to extend them, etc. We should provide this freedom, otherwise it gets too restrictive I think.

**Comment by ivanilas** [comment]
That's why I am talking about a project setting. The project manager may decide whether he needs such restriction or not.

**Comment by jtzikas** [comment]
We could introduce a "close" action that marks an sprint as "closed". When someone closes a sprint it would mean that no one can work on it anymore.
