### ISSUE TITLE
Cannot move uncompleted cards to the next sprint

### ISSUE THREAD

**Issue by ivanilas** [flying-donut/flying-donut-operations#13]
A sprint is finished. There are some uncompleted cards. I can't find an easy way to move those cards into the next sprint.

The only way I can see is to edit the planning of the previous sprint, move the cards into the backlog and then move them again into the active sprint. This is a lot of work.... Furthermore I cannot have insight about the real work of the previous sprint (because the cards are not there any more).

Another approach would be to copy the cards (while at planing of the previous sprint), move the copied into the backlog, and finally move them into the active sprint. This is much more work. Furthermore, I loose the discussions.

There should be a way to decline the uncompleted cards and move them to the next sprint.

**Comment by pkouleri** [comment]
JIRA automatically moves open items to the backlog, perhaps we could do something similar.

**Comment by ivanilas** [comment]
If you just remove the card from the previous sprint, the burndown chart is affected, the remaining hours, etc. If it is technically possible, it may be better to have a card appearing in more than one sprint (the old and the active). 

Either way, I would propose to have a project setting, to auto move the cards into backlog, or to the next sprint, and also apply as "Rejected". If the manager doesn't wish to have this done automatically, he should be able to do this easily in the "Review".

**Comment by jtzikas** [comment]
We have been requested to make is easier to move a card from one sprint to another. The feature request can be found in [our user group](https://groups.google.com/forum/?fromgroups#!category-topic/flying-donut-user/feature-requests/0x2wRI-c454).

Regarding uncompleted cards, in scrum, unfinished work is not taken into account when the sprint is completed. There should not be a case where you say that you completed 5 out of 13 story points of the card. If it's not done and you get 0 points for it. You just move it to the next sprint or the backlog.

**Comment by mikekoetter** [comment]
I would like to reiterate the point about the burndown redrawing after moving cards.  My current workflow on the completion of a Sprint, is to move all not started and incomplete cards to an empty bucket in the backlog.  At that point the spint recalculates and redraws, showing a perfect completion.  
This revisionist history makes me look like a perfect planner, however doesn't represent what happened in the sprint.  This portion seems like a bug.

**Comment by jtzikas** [comment]
Well you have a good point there. Keep in mind that whatever you do you will see a burn-down that reaches the target (0). If we keep all the data in there we will have a steep line at the end just because you moved the cards from the sprint to the backlog or the next sprint.

**Comment by icewind666** [comment]
so, what's the result of this discussion?

**Comment by jtzikas** [comment]
The discussion highlighted two issues. 
1. Have an easier way of moving uncompleted card to the next sprint.
2. Keep the history of changes in the burndown chart instead of showing a perfect completion at the end.

We have those in our backlog. The burndown chart calculation is in our priority list now and should be included in one of our next releases.

**Comment by vivekagarwal1984** [comment]
Has this been done?

**Comment by jtzikas** [comment]
Unfortunately the feature request was deprioritized

**Comment by jtzikas** [comment]
The functionality to start/complete sprint has been introduced that takes care of the issue. When you stop the complete you will be asked what you want to do with the incomplete cards. You may move then to a next sprint or the backlog.
