### ISSUE TITLE
Would like to hide completed cards from the Task Board

### ISSUE THREAD

**Issue by mikekoetter** [flying-donut/flying-donut-operations#14]
Is there or can there be a way to hide completed cards from the Task Board?

**Comment by jtzikas** [comment]
We tested it when we where trying out different approaches with the task board, but the outcome was not good. We where loosing visibility of the task board and what everybody in the team had accomplish.

But we could add it as an option just like the "My Tasks" and "Unassigned".

**Comment by mikekoetter** [comment]
yeah I would definitely make it an option instead of the default.
