### ISSUE TITLE
Allocation chart not working correctly

### ISSUE THREAD

**Issue by ivanilas** [flying-donut/flying-donut-operations#15]
We have created cards and put estimations in hours. The cards are assigned to users. The allocation chart shows zero for all users.

It works only if we create tasks and put hours in tasks. But the tasks are created during the sprint by the users.

**Comment by mikekoetter** [comment]
I have found this less than optimal as well.  Sometimes we use just the cards to represent bugs.  To get around this we need to  add and assign a task that says something "fix it" to the card

**Comment by jtzikas** [comment]
The allocation chart has been taken out of the new version.
