### ISSUE TITLE
I would be nice if there is a chatroom

### ISSUE THREAD

**Issue by ivanilas** [flying-donut/flying-donut-operations#16]
It would be really nice if there could be a chat engine, or integration with another chat engine. Also video calls would be great!

**Comment by mikekoetter** [comment]
We are currently using #Slack as our chat engine.  We have both Slack and Flying Donut integrated with Github so any card creates or card related commits trigger a Slack message, that couple with the Github comments accomplishes most of our chat communication needs.

**Comment by jtzikas** [comment]
Closing this issue as out of scope for the Flying Donut
