### ISSUE TITLE
I can't follow standalone tasks

### ISSUE THREAD

**Issue by ivanilas** [flying-donut/flying-donut-operations#18]

**Comment by jtzikas** [comment]
Hi,
This is the behavior that we have in place for the `Standalone Tasks` card. 
- You can't assign the `Standalone Tasks` card to anyone.
- You can't follow the `Standalone Tasks` card to anyone.
- You can't follow the tasks.

The only way to follow a specific `task` in the `Standalone Tasks` is to convert it to a card and work on it as you would with a regular card. To do so you need to select `Convert to card` in the `task` dropdown.

Let us know if the proposed workaround works for you.

**Comment by ivanilas** [comment]
Yes that works for me. Thanks!
