### ISSUE TITLE
Error while deleting task

### ISSUE THREAD

**Issue by ivanilas** [flying-donut/flying-donut-operations#2]
I deleted a task within a card on the Task Board.
The task remained there even after 4-5 seconds. I tried to delete it again and then the system logged me out. After logging in again, the task was not there.

**Comment by jtzikas** [comment]
We suspect that one of our queues (that was failing at the time) was not able to refresh your board causing it to give you a challenge for user credentials. 

The delete went through though. We are closing this issue for now since it looks like a one time incident.
