### ISSUE TITLE
Descriptions in cards show [object] in Activity Stream instead of the actual text

### ISSUE THREAD

**Issue by jtzikas** [flying-donut/flying-donut-operations#20]

**Comment by icewind666** [comment]
anyone works on this?

**Comment by icewind666** [comment]
Bug opened at 22 Aug! Toady is 21 Dec and no results

**Comment by jtzikas** [comment]
You are absolutely right. It has not been the desired outcome to have these open for so long. Those bugs have been going in and out of our priority list. We hope this one will be released right after Christmas.

**Comment by icewind666** [comment]
Ok. great to see that development is not stopped :)
