### ISSUE TITLE
Sometimes it won't focus

### ISSUE THREAD

**Issue by icewind666** [flying-donut/flying-donut-operations#23]
Sometimes when I click on icon where displayed how many card are done (1/2) it wont focus on card. And the Focus in Actions doesn't work also. 
Here is error I get in javascript console:
Uncaught TypeError: e(...).modalmanager is not a function
t.init  @   bootstrap-modal.js:19
t   @   bootstrap-modal.js:19
(anonymous function)    @   bootstrap-modal.js:19
jQuery.extend.each  @   jquery.js:26
jQuery.fn.jQuery.each   @   jquery.js:26
e.fn.modal  @   bootstrap-modal.js:19
o.extend.show   @   main.js:7
(anonymous function)    @   main.js:7
r.execCb    @   require.js:7
n.check @   require.js:7
n.enable    @   require.js:7
n.init  @   require.js:7
(anonymous function)    @   require.js:7

**Comment by jtzikas** [comment]
We just deployed a patch with the missing dependency
