### ISSUE TITLE
Comment in discussion on card disappeared

### ISSUE THREAD

**Issue by icewind666** [flying-donut/flying-donut-operations#24]
Somehow my long comment on card is disappeared now.
Very strange and bad.

**Comment by jtzikas** [comment]
Could you try clearing your browser cache and refresh? If that does not work please send the card id and the project name (or the url when in focus) to support@flying-donut.com. It will help us to do a better investigation.

**Comment by jtzikas** [comment]
As a followup to your incident. Where you creating a new comment in edit mode as a reply to an existing one or an existing comment disappeared from the list of comments?

**Comment by icewind666** [comment]
It was an existing one. It was the only one comment to this card. I cant really tell if it wasn't actually sent to server side, but I closed that card, open another, and the got back - and it was there. And when I Closed the entire browser and logged in - its gone. 
However, now I cant repeat this behaviour so I think this issue can be closed until something same happened.
