### ISSUE TITLE
Account avatar disappeared

### ISSUE THREAD

**Issue by icewind666** [flying-donut/flying-donut-operations#25]
Account avatar disappeared and wont show anymore.
And I cant set new one too.

**Comment by jtzikas** [comment]
We tested your avatar and it looks good. We cleaned up the cache for you to refresh the page.
When you say you can not set a new one, could you provide more info?

**Comment by icewind666** [comment]
![image](https://cloud.githubusercontent.com/assets/12281362/12020253/4ac2e916-ad8b-11e5-84b8-61556f64b187.png)
I mean this

**Comment by icewind666** [comment]
and this. 
![image](https://cloud.githubusercontent.com/assets/12281362/12020266/6dd1ac9e-ad8b-11e5-80c2-165da8769311.png)

**Comment by icewind666** [comment]
On the last image the picture is not blank. I mean the source picture that I choose.

**Comment by icewind666** [comment]
More info.
What I see in console is that upload was successful
{ "status" : "success" , "url" : "56814d4ce4b0294feedff8e1" , "width" : 259 , "height" : 259}

But then 
Request URL:https://www.flying-donut.com/fdo/user/avatar/file/56814d4ce4b0294feedff8e1
Returns nothing.

**Comment by jtzikas** [comment]
When you try this link http://www.flying-donut.com/fdo//user/avatar/file/5680df63e4b05fbd76063abd/30 what do you see?

**Comment by icewind666** [comment]
by this link all ok, there is my avatar 

-------- Исходное сообщение --------
Отправитель:Ioannis Tzikas notifications@github.com
Отправленные:Mon, 28 Dec 2015 18:06:19 +0300
Получатель:flying-donut/flying-donut-operations flying-donut-operations@noreply.github.com
Копия:Vladimir vladimir.korennoy@gmail.com
Тема:Re: [flying-donut-operations] Account avatar disappeared (#25)

**Comment by jtzikas** [comment]
If you go to a project is your avatar loaded in the activity stream? 
Refresh the project dashboard page and let us know if the avatar is loaded in the menu. Then navigate to the "manage account" page to the "avatar" tab and let us know what you see there.

Important. Refresh only when in the project page.

**Comment by jtzikas** [comment]
I forgot to mention that the url you provided https://www.flying-donut.com/fdo/user/avatar/file/56814d4ce4b0294feedff8e1 returns your avatar correctly.

It could be a caching/loading issue that sneaked in. So far I could not reproduce the issue.

**Comment by icewind666** [comment]
I guess so, now its ok
