### ISSUE TITLE
Sprint Burndownd chart is always and only in UTC

### ISSUE THREAD

**Issue by gianei** [flying-donut/flying-donut-operations#26]
This causes graph to be splied in the middle of my workday.

It could use correct timing such as there is in Project Activity Stream

**Comment by jtzikas** [comment]
You can change the timezone of the project that is driving the burndown chart. To change it go to the project settings modal: 

![Image](https://sc-cdn.scaleengine.net/i/f979865b9e3d4b3b2e8c3804cd42e0011.png)
![Image](https://sc-cdn.scaleengine.net/i/ed349a099d48f896c1aad45cd32add0e.png)

**Comment by gianei** [comment]
Thanks! I didn't notice this menu.

Maybe it would be nice to add a few and simple description about these available project settings in that project description created in the default project... specially about Time Tracking (I just found out now why my commits with -spent time were not adding any data to the tasks)

**Comment by jtzikas** [comment]
Great to hear that it worked out. 

I agree that the docs we have in place have been outdated in lots of places since the product has moved forward. I will notify the team with your feedback.
