### ISSUE TITLE
bitbucket integration problem when merging pull requests

### ISSUE THREAD

**Issue by ivanilas** [flying-donut/flying-donut-operations#28]
Α pull request with id 108 was merged into master (the PR id is generated by bitbucket).

We have a task with the same id. 

flying donut associated the commit of the PR with the task. 

This should not happen.

**Comment by jtzikas** [comment]
Setting up the integration with bitbucket webhooks resolves the issue. Don'f forget to remove the POST service before creating the new webhook.
