### ISSUE TITLE
Wrong email notification received

### ISSUE THREAD

**Issue by ivanilas** [flying-donut/flying-donut-operations#32]
My coworker created a card and 2 tasks in it. He assigned the card to me. I then moved a task from todo -> Doing. I received then an email notifying me that my coworker changed card status to "in progress". But it was me who did the change.

**Comment by jtzikas** [comment]
This bug was introduced right after the milestones feature.
Thanks for reporting.

**Comment by jtzikas** [comment]
The issue has been fixed and deployed to production
