### ISSUE TITLE
API endpoint for Milestones

### ISSUE THREAD

**Issue by mikekoetter** [flying-donut/flying-donut-operations#33]
There doesn't appear to be an api endpoint for milestones

I see that the milestone oid is included in the sprint objects, is there an existing uri for milestones that I am just not seeing?

**Comment by jtzikas** [comment]
The milestones are not exposed in the API yet. It is next in our priority list and will be included in a couple of sprints. Is it something you need earlier?

**Comment by mikekoetter** [comment]
If we could get it earlier that would be great.  we are building or roadmap
gantt around it.
If it is not available, I will stub it and hardcode it in the interim.

**Comment by jtzikas** [comment]
Milestones are exposed in the API from now on. Tested and released on production.
