### ISSUE TITLE
In backlog problem when moving cards to another bucket

### ISSUE THREAD

**Issue by ivanilas** [flying-donut/flying-donut-operations#34]
In backlog, I moved some cards from one bucket to another. When refreshing the backlog I don't see the changes. When going to the "Planning" of a sprint, I see the change.

**Comment by jtzikas** [comment]
Do you still have an issue? It could be a temporary browser caching issue

**Comment by jtzikas** [comment]
It is related to the browser cache and a failed cached invalidation. Closing it for now as a temporary issue until we verify a more general issue with our cache invalidation rules.
