### ISSUE TITLE
URGENT: Recover a deleted project

### ISSUE THREAD

**Issue by cguttmann** [flying-donut/flying-donut-operations#35]
Hello, I accidentally deleted a project called "HealthiHabits Admin". 
Could you please recover it?
Thank you, Christian

**Comment by jtzikas** [comment]
For the history, we had a direct contact with cguttmann.
Unfortunately the delete action, that was performed, erased the project permanently from the database. The action to restore the project from a backup was more time consuming than putting the information from scratch.
