### ISSUE TITLE
Enhancement - Minimize bucket cards in the Backlog

### ISSUE THREAD

**Issue by justin-sandoval** [flying-donut/flying-donut-operations#36]
I was curious if there could be an enhancement to minimize all the cards to it's particular bucket.  For example I have a bucket called Design.  I have 20 cards in the list.  Could the page load to minimize all the cards when the page loads.  The purpose of this enhancement is to not have to keep scrolling over other bucket card items that I don't want to see.

**Comment by jtzikas** [comment]
We only show the active bucket in the backlog in the new version that was deployed a few days ago. It prevents the scrolling you mention in the issue.
