### ISSUE TITLE
Filter tasks/items owned by other team members

### ISSUE THREAD

**Issue by tsegi** [flying-donut/flying-donut-operations#38]
During scrum meeting we have our scrum master (which is also one of the developers) open FlyingDonut project space and update it while others report task status and time to complete. But when the scrum master tries to locate a task for the team member who is reporting his status, it is difficult because there is no way to filter for tasks owned by other members. Would be nice to have such feature.

**Comment by jtzikas** [comment]
It is a valid feature request and we have already added a similar request to our backlog. One question though. How come the people working on the tasks don't update the status of the tasks themselves?

**Comment by tsegi** [comment]
Sorry for replying late.

The people do update the tasks individually, but our use case is like: During daily scrum meeting, the scrum master will project the "Planning" view of Flying Donut on the screen and go through the items' status together. If any task has not yet been updated yet, the scrum master will do so on the spot, to save time for the team member to go back to their desk, find the task again and update that.

**Comment by jtzikas** [comment]
I just wanted to let you know that the filtering feature in the board and backlog is already available. It includes options for assignees, labels, and text, so you can easily find what you're looking for.
