### ISSUE TITLE
Flat burndown

### ISSUE THREAD

**Issue by ToLive** [flying-donut/flying-donut-operations#39]
![ticket20170418_0922_1109](https://cloud.githubusercontent.com/assets/2019736/25112038/d9ec03fc-2418-11e7-968f-c35fd4836c74.png)
I have a flat burndown diagram, but some tasks are already in "Done" section. What I'm doing wrong?

**Comment by jtzikas** [comment]
Hi,
It looks like you only have cards in your board, thus you get a flat burn down chart. At this point of time, the progress of the burn down chart is calculated based the the tasks of the cards. To make the burn down chart work correctly you need to add tasks to your cards. 

![image](https://cloud.githubusercontent.com/assets/2730604/25119317/5adba93c-2422-11e7-92e8-670cddc92572.png)

We've already added a new feature to our priority backlog to calculate the progress of task-less cards in the burn down charts that will solve your issue.

**Comment by ToLive** [comment]
Thank you! You are right, I have decomposed tasks as cards. I will add some fake tasks to cards to complete them.
