### ISSUE TITLE
Dashboard Discussions clickable

### ISSUE THREAD

**Issue by ivanilas** [flying-donut/flying-donut-operations#4]
In the discussions pane on the dashboard, I would like to be able to click on the discussions and open them. For example I have an entry : "xxx created discussion "mongodb or redis?" It is impossible to know, in which project and which task / card the discussion is created. I have to search the whole projects and cards!

**Comment by jtzikas** [comment]
This is issue is no longer valid. The discussions are not part of the dashboard. Discussions that are of importance are sent via email with a link to the discussion instead.
