### ISSUE TITLE
API error: Fetch Sprints not working (500 error)

### ISSUE THREAD

**Issue by johannes-seamonster** [flying-donut/flying-donut-operations#41]
I'm testing out Flying Donut and one thing that is awesome (as it's a critical requirement) is the API to query Project data. I activated the API and generated a key, and with Postman I can fetch Project details, but when I try api/projects/xxxxxxx/iterations, I get a 500 error. Everything else like milestones seem to work fine, but without being able to fetch the sprints I'm a bit stuck: I can't get the sprint ids and therefore can't get the items or burndown or anything else.

Is this a known bug at the moment, or am I missing something?

Thanks!

**Comment by jtzikas** [comment]
It is an authorization bug that you encountered. We are fixing it as we speak.

**Comment by johannes-seamonster** [comment]
Great! Thanks for the feedback! Any ETA on the update?

**Comment by jtzikas** [comment]
It has been fixed. Please try again and let us know.

**Comment by johannes-seamonster** [comment]
Works perfectly! Thanks!
