### ISSUE TITLE
Can Assign a user multiple times to the same task

### ISSUE THREAD

**Issue by danielhorne** [flying-donut/flying-donut-operations#42]
On the sprintban board, while in the assign to menu for a task if you click quickly on the same user assigns them multiple times to the same task.

**Comment by jtzikas** [comment]
Yes this is a bug indeed. It will be resolved.
Thanks for reporting.

**Comment by danielhorne** [comment]
Sure thing. I am really enjoying the app so helping where I can.

On 23 Oct 2017 6:50 p.m., "Ioannis Tzikas" <notifications@github.com> wrote:

Yes this is a bug indeed. It will be resolved.
Thanks for reporting.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/flying-donut/flying-donut-operations/issues/42#issuecomment-338723468>,
or mute the thread

**Comment by jtzikas** [comment]
We just deployed a fix. 
You could give it a try again and let us know.
