### ISSUE TITLE
Approval event in the Activity Stream

### ISSUE THREAD

**Issue by Garikolc** [flying-donut/flying-donut-operations#45]
Hi Ioannis,
Could it be possible for you to add the approval of a card in the Activity Stream?
A greater solution could be allowing the user to select the information shown on the Activity Stream.

**Comment by jtzikas** [comment]
Sure we will add the approval actions in the activity stream. 
Regarding the solution to allow the user to select the information shown on the Activity Stream will be taken into account and we will create a new feature request in our backlog. It is a nice feature to have.

**Comment by jtzikas** [comment]
The approval event is visible now in the activity stream of version 2.x of Flying Donut
