### ISSUE TITLE
Enhancement: allow project integrations with multiple repositories

### ISSUE THREAD

**Issue by gitanoqevaporelmundoentero** [flying-donut/flying-donut-operations#46]
In our company we are currently facing the problem that some of our projects require new developments in multiple software repositories. Furhtermore, some of our sofware repositories are involved in multiple scrum projects. We are having 2 different problems working with FlyingDonut and its integrations with Gitlab repositories (it would be the same working with GitHub or Bitbucket integrations):

- If one repository is linked (via integration) to multiple FlyingDonut projects, there is no way for assigning an specific commit to an specific FlyingDonut project. For example, if we use a commit message like `#{id} -spent 1h`, all of our active FlyingDonut projects having a card/task with "{id}" number would be updated (and not only the card/task belonging to the desired project)
- We haven't found a way for including multiple integrations to different software repositories in a single FlyingDonut project. Our solution involves the creation of multiple specific subprojects, one for each software repository, thus lacking the general background that would be included if working with a single project.

It would be nice to include both functionalities:

- Possibility of specifying the FlyingDonut project in commit messages
- Enabling multiple software repository integrations for a single project

**Comment by jtzikas** [comment]
Hi, 
Regarding the first request (Possibility of specifying the FlyingDonut project in commit messages) we are thinking about the best way to support it. It is already in our to-do feature list, but I can't say when it will be supported.

Regarding the second request (Enabling multiple software repository integrations for a single project) I'm happy to say that it is already supported. You just need to add the same webhook Payload URL in the repos you want to integrated with. 

For example, if you have multiple gitlab repos, then you enable the gitlab integration for the project in Flying Donut. Then you create a webhook for each of the gitlab repos with the same Payload URL that was generated.

**Comment by jtzikas** [comment]
The project key feature is available now in the admin project setting of version 2.x of Flying Donut. You can use it to use the same repository linked to multiple projects. The card/task ids will look like "OPS-578" that can be used in the commit messages. If you leave the project key empty the ids will have their default format "#578"
