### ISSUE TITLE
Cards don't go to done state if i commit with: #3 -done

### ISSUE THREAD

**Issue by tpoth** [flying-donut/flying-donut-operations#48]
If i do a commit message with the following content normally the Card should be put in Done state.

`#3 -done`

Therefore the `#3` is a Card in FD, which is in Testing state.

The Project is setup as Scrumban.
I've put GitHub integration to work properly.
Task will be closed well, if i do the same with a Task id instead of a Card id after the pound symbol.

If you want to have a look into the project, the project is public at:
https://www.flyingdonut.io/app/boards/62c01019dda1b70b2e5a07a6

Maybe this is a bug or you have a workaround for this Issue.
Thanks alot in advance.

-Thomas

**Comment by jtzikas** [comment]
Hi thanks for reporting your use case. We will have a look why the `-done` command is not working as expected.

**Comment by jtzikas** [comment]
The issue has been fixed and is working as expected now.
Could you verify that it works for your project as well?
