### ISSUE TITLE
I would like to be able to open (focus) a card as a separate page

### ISSUE THREAD

**Issue by ivanilas** [flying-donut/flying-donut-operations#8]
I would like to be able to right click -> open in a new tab (or ctrl+click) a card and open it in a new tab. That way, I will have a full screen of the card with all details, description, discussions, and lanes of tasks to move (todo - in progress - done)

**Comment by jtzikas** [comment]
Now you have the all details in the modal details view. We are working on producing the new tab functionality.

**Comment by jtzikas** [comment]
We added the functionality to open a new tab with the card including the board in the background
