### ISSUE TITLE
I would like to reference cards/tasks

### ISSUE THREAD

**Issue by ivanilas** [flying-donut/flying-donut-operations#9]
When editing the title of a card/task or the description of a card, I would like to be able to create a reference to another card/task

**Comment by tsegi** [comment]
Would be nice if this feature works across project spaces for easier collaboration. e.g. I have two projects which are related but members are different (due to the original project's size we split into two teams).

**Comment by jtzikas** [comment]
The linking of cards and tasks across projects is something that we have in our plans.

**Comment by jtzikas** [comment]
Closing this issue as linking of cards and tasks is available in all markdown texts
